# Generated by Django 3.2.3 on 2021-05-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pvgis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('lon', models.IntegerField(max_length=25)),
                ('lat', models.IntegerField(max_length=25)),
                ('slope', models.IntegerField(max_length=25)),
                ('azimuth', models.IntegerField(max_length=25)),
                ('technology', models.CharField(max_length=25)),
                ('peakPower', models.IntegerField(max_length=25)),
                ('loss', models.IntegerField(max_length=25)),
            ],
        ),
    ]
